@host=http://localhost:5238

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJjMjRmMjMwYy0yMzlhLTRhMDAtOWNhNy0yOTIwZjFjYWM0YWMiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiU21pdGgiLCJlbWFpbCI6ImpvaG5Ac21pdGguY29tIiwianRpIjoiNjk0YTIyNDMtOWU5Mi00ZjEyLTk5NzgtZjZhMGUyOTY0MDllIiwiZXhwIjoxNzEzNjY4NDk2LCJpc3MiOiJQU0Rpbm5lciIsImF1ZCI6IlBTRGlubmVyIn0.tb80oSY4Vp4ZdzU6tDz-DZPX0-Xygz0I9YNOs-JI9vI